export default {
  data: [
    "ACB Ingeniería",
    "Aceleración Labs",
    "Active IT Chile",
    "Adexus",
    "ADP Chile",
    "Advise",
    "Agile Ingeniería y Consultoría",
    "Akzio",
    "Alaya Consultores",
    "AlfaPeople Chile",
    "ALMA-ITS",
    "Altiuz Chile",
    "Amisoft",
    "Andes IT",
    "Angecom Technologies",
    "Anida TI",
    "Apiux",
    "Applicatta",
    "Aquanta",
    "Arbol Logika",
    "Arkano",
    "Arkhotech",
    "ARSbyr",
    "Artikos",
    "Asicom",
    "Atica Ingeniería",
    "Ayesa Chile",
    "Azurian Chile",
    "BackSpace",
    "BBR",
    "BCN Consultores",
    "Bee Mind",
    "Belltech",
    "Bettersoft",
    "Binaria",
    "BinaryBag",
    "Biosoft Chile",
    "Birchman Group",
    "Birdie",
    "Blue Solutions",
    "Builderhouse Ingenieros",
    "Browse Ingeniería",
    "Business Continuity",
    "Business One Consulting",
    "C2C Tecnologías",
    "Catena",
    "CiberGroup",
    "CLAdirect Chile",
    "Clean Code",
    "CMetrix Business Solutions",
    "CMT Latin America",
    "CN Brokers",
    "Coasin",
    "Cognitiva",
    "Coinsa",
    "Comten",
    "Connectis Chile",
    "Contal",
    "Contaline",
    "Continuum",
    "Covenco",
    "coreDevX",
    "Creatika",
    "Crecic",
    "CrewValue",
    "CrimsonLogic",
    "CSC-Chile Consultores",
    "Ctrl365",
    "Dapcom",
    "Datactil",
    "Datactiva Group",
    "Dataflow",
    "Datanet",
    "DBNeT",
    "Decalink",
    "Defontana",
    "Desis",
    "Digevo Group",
    "Dimasoft",
    "Dimension",
    "Documenta",
    "Dsac",
    "DTLnet",
    "DTS",
    "Dualnet",
    "ECM Chile",
    "Ecomsur",
    "e-Contact",
    "Editrade",
    "Emeneger",
    "Emergya",
    "eShare Chile",
    "Eugcom",
    "Everis Chile",
    "Exalitica",
    "Exe Ingeniería",
    "Experian",
    "Exxis",
    "Exypnos Consultoría",
    "Facele",
    "FactorIT",
    "Fairware Computación",
    "Flexwin",
    "Genera",
    "Genesys",
    "Geosolve",
    "Geovalidata",
    "Geoxite",
    "Geslim",
    "Global Services",
    "Global System",
    "GovMs",
    "Grupo ASSA Chile",
    "Grupo Cesa",
    "Grupo Sentte",
    "Grupo Taisa",
    "Huenei Chile",
    "I2B Technologies",
    "iConstruye",
    "Imaginex",
    "Imatec Computación",
    "Imatronix",
    "In Motion Consultores",
    "Indecs",
    "Indexa",
    "Infodesign",
    "Infor Software",
    "Informat",
    "Infosecure",
    "InfoWorld",
    "Inpact",
    "Insis",
    "Integrius",
    "Intellego",
    "Intercity Networks",
    "Intesis Chile",
    "Inxap",
    "ISC",
    "IT Consulting",
    "IT World",
    "ITCS Integrated Solutions",
    "ITQ Latam",
    "ITS Smart",
    "IxOpen",
    "KI Teknology",
    "Kibernum",
    "Kio Solutions",
    "KPaz Consultores",
    "Kuvasz Solutions",
    "Lagash",
    "Lanix Technology",
    "Last Call",
    "LatinShare",
    "Laudus",
    "Logicalis",
    "MAB Soluciones",
    "Magens",
    "Manager Software",
    "Manglar",
    "Mastermind",
    "Maximise",
    "Mekano",
    "Microgeo",
    "Micrológica",
    "Microsystem",
    "Miractiva",
    "Miro",
    "Mitocondria",
    "Mobiletouch",
    "Modular Mining Systems",
    "Movix Chile",
    "Multinet",
    "mySolutions",
    "Napsis",
    "Nebulan",
    "Netcomputer",
    "Netglobalis",
    "Netgroup",
    "Nethelp",
    "NetRed",
    "Netsecure",
    "Netsolutions",
    "Neuronet",
    "Newtenberg",
    "Nexsys Chile",
    "Nielsoft Informática",
    "Nisum Chile",
    "NLT Networks",
    "Novared",
    "Novasis",
    "Novis",
    "Nubox",
    "Nursoft",
    "Nuwit",
    "Octalia",
    "OFB Consulting",
    "Oferus",
    "One Consultores",
    "Onvision Group",
    "Opentek",
    "Opta Consultores",
    "Optimisa Informática",
    "Option",
    "Orand",
    "Oxus",
    "PAD Systems Consulting",
    "PartnerTech Solutions",
    "Patagonia IT",
    "Performance HR Consulting",
    "PKI Chile",
    "Plane",
    "PlanOK",
    "Plataforma Group",
    "Platanus",
    "Policomp",
    "Practia",
    "Pragma Informática",
    "Prime Services",
    "Prosoft",
    "Prosystem",
    "Quinaria",
    "Random",
    "Rayen Salud",
    "Rebsol",
    "Red To Green",
    "Redvel",
    "Rezebra Technologies",
    "Rhiscom",
    "Rittal",
    "RMC Consultores",
    "S&A Consultores",
    "Safehis",
    "Salud Innova",
    "SAN Consulting",
    "SEnTRA Software House",
    "Serinfo",
    "Sidekick",
    "Sidge",
    "Siemon Chile",
    "Sisdef",
    "Sistam Ingeniería",
    "Sixbell",
    "Smartcob",
    "Snoop Consulting Chile",
    "SOA BPM – LATAM",
    "Social It",
    "Soft Capital Consulting",
    "Softland",
    "Softline Chile",
    "Solex",
    "Soluciones BI Consulting",
    "Soluciones Orion",
    "SoluforB",
    "Solunegocios",
    "Sonda",
    "SPC Chile",
    "ST Computación",
    "Stacks",
    "Summit Technologic",
    "Synaptic",
    "Synergistics South America",
    "Sypsoft",
    "Technosystems Chile",
    "TechPoint",
    "Techvalue",
    "Tecnocom Chile",
    "TestGroup",
    "TFC Soluciones",
    "TGI Mobile Systems",
    "TI Chile",
    "Tiaxa",
    "TicBlue",
    "TICGestión",
    "Tigabytes Chile",
    "Tisal",
    "Tivit Chile",
    "Transtecnia",
    "Transtel",
    "Trebol IT",
    "Tuxpan",
    "UpSociative",
    "Valentys",
    "Vasslatam Chile",
    "Venturi Consulting Group",
    "Virtual 21",
    "Visual Knowledge",
    "VMICA Sistemas y Tecnología",
    "W Ingenieros",
    "Wisdom HR Consulting",
    "W-IT",
    "Wultu – Isap",
    "XCorp",
    "Xgold IT",
    "XMS Technologies",
    "Xnear",
    "Zenith Consulting",
    "Zenitx",
    "Zecovery",
    "Zeke",
    "Garage Labs",
    "Agilesoft",
    "Pawer",
    "Queplan",
    "Perceptron",
    "Almacén Gurú",
    "SoyFocus",
    "Kipp",
    "eDarkstore",
    "BuyDepa",
    "Clay",
    "WherEX",
    "SoyMomo",
    "Rankmi",
    "POW Foods!",
    "KLog.co",
    "Emonk",
    "Cero",
    "Cotalker",
    "Clever",
    "Bifidice",
    "Andes STR",
    "Encuadrado",
    "Copper3D",
    "Rendalo Maq",
    "Kaudal",
    "Comunidad Feliz",
    "Andes",
    "Nutrix",
    "Toku",
    "TIMining",
    "Wurú",
    "Xepelin",
    "Yu-Track",
    "Quansa",
    "Indimin",
    "Global66",
    "Aintech",
    "Examedi",
    "Betterfly",
    "Done Properly",
    "Vita Wallet",
    "Webdox",
    "Phage Lab",
    "RePhone",
    "Lomi",
    "GenoSUR",
    "Kredito",
    "Taloo",
    "Flayyer",
    "TRAINFES",
    "Cicla 3D",
    "Capitalizarme",
    "Buda",
    "AgroUrbana",
    "Fintoc",
    "Archimaker",
    "Strong by Form",
    "Muvu",
    "AgendaPro",
    "SharpShark",
    "PolyNatural",
    "Videsk",
    "Justo",
    "Storkall",
    "IT-Talent",
    "Smart CFO",
    "Buk",
    "Karün",
    "Houm",
    "UNK Latam",
    "GeoVictoria",
    "Jooycar",
    "Pago Fácil",
    "Khipu",
    "Fracttal",
    "Admetricks",
    "Poliglota",
    "SimpliRoute",
    "FirstJob",
    "Autofact",
    "Kappo Bike",
    "Ipsum",
    "Lexgo",
    "Neat",
    "Postedin",
    "CFOremoto",
    "Hackmetrix",
    "Chipax",
    "Zippedi",
    "Adereso",
    "Get on Board",
    "Green Glass",
    "ServiSenior",
    "OKtoShop",
    "Fracción",
    "Lab4U",
    "Cumplo",
    "Protera",
    "Instacrops",
    "Wheel the World",
    "Algramo",
    "Solubag",
    "Welcu",
    "u-planner",
    "F4F",
    "Crystal Lagoons",
    "Cornershop",
    "Archdaily",
    "MACH",
    "NotCo",
    "Fintual",
    "Recorrido",
    "ChileTrabajos",
    "GoPlaceIt",
    "Beetrack",
    "Houm",
    "Edipro",
    "Reservo",
    "PuntajeNacional",
    "Fracttal",
    "Destácame",
    "SimpliRoute",
    "Epistemonikos",
    "DENTIDESK",
    "Denomades.com",
    "Babytuto",
    "QuePlan.cl",
    "Rankmi",
    "Lemontech",
    "2x3",
    "ERPyme",
    "SOSAFE",
    "PostedIn",
    "DataScope",
    "Denda",
    "Edoome",
    "Wivo",
    "Eco Hosting",
    "Rodati.cl",
    "Ror Deco",
    "Airkeep",
    "zimplePR",
    "Suda Outdoors",
    "Fanear",
    "En 1 Mes",
    "Certificadas",
    "Edifácil",
    "Yunke",
    "Roier.ai",
    "Voyhoy",
    "PropiedadFacil",
    "RedAlmacen",
    "Blinking",
    "Rides CL",
    "HackerHand",
    "Facturedo",
    "RedCapital",
    "LoHaria",
    "TINK",
    "SoyMomo",
    "Weeshing",
    "Obzes",
    "TIClass",
    "SOSmart",
    "Yoy Simulators",
    "Emprenet",
    "DesRueda",
    "Adere.so",
    "EntrenaYa Chile",
    "SocialWeb",
    "Joldit",
    "Uanbai",
    "TrainFES",
    "Austral 3D",
    "Agronometrics",
    "HuevoHost",
    "Qué hacer en Santiago?",
    "Nacionales",
    "frisbi",
    "Salones&Eventos",
    "AmberAds",
    "InstaGIS",
    "Uper",
    "Bolsa Emergente",
    "Mobot",
    "GameLab Education",
    "Derecho24",
    "SattaProject",
    "Purplu",
    "Tooldata",
    "moviezplus.co",
    "Talento al Aula",
    "Lean Testing",
    "Run.cl",
    "Nearway",
    "Awesomi",
    "RocketAd",
    "Cuida.me",
    "Primero Cotiza",
    "TourDesk",
    "SatisFactor",
    "Pivto",
    "AlóProfe",
    "Mallbits",
    "Claneco",
    "Sazoot",
    "Lab4U",
    "SlidePick",
    "Ciudad Fácil",
    "MyHood",
    "QueHambre.cl",
    "TWSocial",
    "Pipol",
    "Seahorse",
    "Deemelo",
    "Divino Descuento",
    "BabyShop.cl",
    "Beeok",
    "Dodo",
    "Caaapital",
    "Truequers.com",
    "BancoIdeas",
    "Mozcu",
    "RockYourPaper",
    "Guubie",
    "Fuud",
    "Tralov",
    "Pindapps",
    "CrowdTransfer",
    "Zhipcode",
    "VitaNocturna",
    "Aid App",
    "Uniquisimo",
    "Vendetu",
    "Hoblee",
    "Bissen",
    "KewenApp",
    "Wapas",
    "LaunchCard",
    "Importa y Exporta",
    "NetUP",
    "Restorius",
    "Zona Avisos",
    "Eollice",
    "InstaRespuesta",
    "Como En Tu Casa",
    "Mootree",
    "CatedrasLibres",
    "LoCambio",
    "Mobile Legem",
    "UPA!",
    "WordUp Games",
    "Eduquia",
    "Work4ce.me",
    "Blumee",
    "VerdeMagenta",
    "Fugate",
    "Reciclata",
    "LiveTrust",
    "Sirias Salud",
    "CultureStay",
    "Ayudantee",
    "Comcarga",
    "Kauk'en",
    "WeLive",
    "Potencial Digital Chile",
    "LatAm Buses",
    "Reinsystem",
    "Weddi.cl",
    "Profitek",
    "The Coffee Kit",
    "Gluh",
    "Hostingmania",
    "CloseJob",
    "PractiJob",
    "E-nterview",
    "TheSocial.bet",
    "TrabajoPanel",
    "AlfombraMagica",
    "Mamabox",
    "Sellywhere",
    "Smartour App",
    "Vetnovo",
    "dooParty",
    "WiroTV",
    "Buildnex",
    "Ohmygift!",
    "The Printlab",
    "Foodland.cl",
    "Rentag",
    "Centro Comercial 14",
    "Belleza Interior",
    "Prensa Web",
    "Baobab",
    "MyZalud",
    "MasteringCoding",
    "zuppbox",
    "Radio Triama",
    "RaiseUp",
    "qrlabs",
    "Eaprende",
    "Receta inteligente",
    "StartupNow",
    "Coin4ce",
    "Vincoli",
    "Mapea Chile",
    "Boabo.cl",
    "Abrevia",
    "Jooks",
    "EMcube",
    "Globant",
    "Mercado Libre",
    "AFP Modelo",
    "MediaStream",
    "Ilogica",
    "SociaLab",
    "Symbiose",
    "ComparaOnline",
    "Banco BICE",
    "eClass",
    "Moodbit",
    "Jumpitt",
    "Nekki",
    "Clyc.me",
    "Tech-K",
    "Carsales",
  ]
}
